## Oh My Zsh config

ZSH_THEME="robbyrussell"
HYPHEN_INSENSITIVE="true"
ENABLE_CORRECTION="true"
HIST_STAMPS="yyyy-mm-dd"

ZSH_CUSTOM=/usr/share/zsh

plugins=(
  git
  go
  cargo
  rust
  archlinux                  # TODO: change to your specific OS
  command-not-found       # Get suggestions for missing binaries
  zsh-autosuggestions     # Command suggestions while typing
  zsh-syntax-highlighting # Different colors while typing
  colored-man-pages       # "man" command now prints in color
)

fpath=(/usr/share/zsh/plugins/zsh-completions/src $fpath)

source $ZSH/oh-my-zsh.sh

## Prompt

if [[ $(id -u) == 0 ]]; then
  PROMPT="%{$fg_bold[red]%}%n%{$fg_bold[white]%}@%m%{$reset_color%} ${PROMPT}"
else
  fortune -s | cowthink -f tux -W 40
  PROMPT="%{$fg_bold[black]%}%n%{$fg_bold[white]%}@%m%{$reset_color%} ${PROMPT}"
fi

## Custom Aliases

alias steam="$HOME/.local/bin/steam"

alias mv="mv -iv"
alias cp="cp -iv"
alias szsh="ZSH_DISABLE_COMPFIX=true sudo --preserve-env zsh"
alias quit="exit"

alias gt="glog"
alias gta="glog --all"
alias gth="glog HEAD"
alias gpk="git push fork"
alias gpkf="git push fork -f"
